### ISSUE TITLE
Enhanced vs unenhanced Apple //e and font selection

### ISSUE THREAD

**Issue by patdie421** [ThorstenBr/A2DVI-Firmware#12]
Hi,
I have a small display issue in PROCEL (v4) when the "enhanced font" is enabled :
![photo1](https://github.com/user-attachments/assets/c4f55def-6c04-4b9b-96c0-0a910f727070)
![photo2](https://github.com/user-attachments/assets/0a6fc5c0-06b6-4f8c-9a58-ee969cdeff84)
I use firmware 1.2 on a self assembled A2DVI v2.0 with RP2040.
On an A2VGA card with A2RetroComputing/Analog Firmware version 20230504 the display is OK (alpha characters correctly display in inverse mode), so I think that the issue is not linked to PROCEL software.
Let me known if you need more informations.
Regards,
Patrice

**Comment by ThorstenBr** [comment]
What you see is the "mousetext" characters of the enhanced fonts. The enhanced IIe has a register to toggle the display behavior: either support flashing characters or support "mousetext" characters. The image above looks like the program wanted to show flashing text - but "mousetext" is enabled instead.

I don't see any issues with the flashing vs mousetext switching on my machine.

Post a screenshot of what you have enabled in the configuration menu. Also, enable the "debug monitor" option. Then start the program - and look in the top right corner of the screen. When the soft switch "**ALTCHAR**" is visible in the top right corner, then "mousetext" is selected (otherwise flashing text is selected).

Another test: when the screen issue appears, press CTRL-RESET and then:
```
] CALL -151
* C00E:1
* C00F:1
```

=> C00E and C00F are the registers to disable/enable mousetext (enable/disable flashing text).

**Comment by patdie421** [comment]
Hi, thank you for your response, it allowed me to find the cause of my problem.
The screenshots above were taken on a "non-enhanced" Apple 2e with a 6502 processor and base ROMs.
The card does not seem to automatically differentiate between Apple 2nd generations (I don't know if it could) and therefore the behavior of an application that uses mouse characters is not predictable.
I tested on my 2e platinum and it works as expected.
sorry for bothering you about that and thank you once again.
Regards

**Comment by ThorstenBr** [comment]
Ok, no problem.
Yes, if you have an unenhanced IIe, then you need to select "unenhanced" fonts. The unenhanced ROMs are probably not resetting the softswitch, as the newer ROMs would.
The A2DVI is actually able to detect whether it's an enhanced or unenhanced IIe. It can tell the difference of the ROMs. However, currently it doesn't make any difference. Both are just detected as "IIe".
Yeah, it might make sense to change the menu and differentiate the machine type "IIe enhanced" vs "IIe unenhanced". The font selection (enhanced/unenhanced) would then not be necessary any longer.

I'll need to think about that... :)
