### ISSUE TITLE
Intermittent corruption on boot

### ISSUE THREAD

**Issue by StormTrooper** [ThorstenBr/A2DVI-Firmware#18]
I've just build one of these any using the latest firmware 1.6

On first bootup there was no splash screen and it booted straight into the Apple ][ prompt. 

And the next bootup though, and now seems to happen 50% of the time I get booted into the splash screen (Which is perfect) and after  a few seconds I get a screen full of corrupted characters. 

Any idea what is causing this?

Running on a Apple IIe with the original RBP Pico. 
Apple IIe passes all diagnostics, no memory issues. I have been using it with a different RBP Pico VGA adapter without issues. 

Are there any other details I can provide which can help solve this?

![20241117_165608](https://github.com/user-attachments/assets/d1fbccc0-aeb4-47f0-add2-a4148f4e9b89)

![20241117_165610](https://github.com/user-attachments/assets/da34ee70-b676-43f0-8281-90c78130bcaf)

**Comment by ThorstenBr** [comment]
The splash screen should not become visible when the Apple II boots normally. It should display the Apple II prompt immediately.

The splash screen remains visible, at least for a few seconds, when the no normal Apple II boot sequence is detected - to help with diagnosing the issue.

While the splash screen/diagnostics are visible:

* You should see the "BUS CYCLES" counting (1 million cycles per second). If that is not the case, then you have a hardware issue with the Phi0 connection. The PICO is unable to see the rising/falling edge of Phi0. 
 
* You should also see the current value of the address bus (updated several times per second). In your photo it shows "FFFF", which is concerning. Might be an issue with the address bus connection - or just a result of the PICO not detecting any bus cycle (due to an issue with Phi0), so the address bus isn't even read/updated.

In any case looks like a hardware issue with the slot/bus connection. Or an issue with your bus transceivers, which make the connection between the PICO and the 6502 bus.

**Comment by StormTrooper** [comment]
Thanks for the info. 

I've cleaned the connections  and also tried a different bus. 

The bus cycles is counting.
There are 2 issues on the address bus, it's either stuck at FFFF or it's changing, or it just boots fine. About 1/3. 

I'll change out the bus transceivers and see if it makes any difference.  (Or maybe build another device as it might be quicker)

**Comment by ThorstenBr** [comment]
Make sure to use proper 74**lv**245 devices (3.3V). I have seen reports of people claiming they have received fake ICs, maybe relabeled LS245s, from dodgy sources.

**Comment by StormTrooper** [comment]
I've re-ordered NXP 74LV245 chips from the official distributor so hoping it fixes it. The previous batch were from eBay so maybe dodgy.

**Comment by StormTrooper** [comment]
Chips replaced and it's made a improvement. Still getting the corrupted screen but it's a lot less now. Maybe about 1 in 10 startups is corrupted. 

Happy to live with this and close the issue as it's working 90% of the time.

**Comment by ThorstenBr** [comment]
Just to correct myself, since I wrote "LV245" above: the correct part for the transceiver buffers is "LVC245", as given in the schematics, which is a much faster variant. The A2DVI firmware relies on the fast device, since it needs to switch very fast between the three buffers to access two address bus + data bus bytes. The LVC245 guarantees response times below 20ns. Other devices, such as LV245 are much slower, and would not guarantee this timing, according to the data sheets. And HC245s would be even slower. So using the correct part for A2DVI boards does matter, as the firmware actually relies on the fast timing when switching the buffers.
